// Generated by CoffeeScript 1.4.0
(function() {
  var circle, radius;

  require("coffee-script");

  circle = require('./circle');

  radius = 1;

  console.log("circ with radius =1 :", circle.area(radius));

}).call(this);
