// Generated by CoffeeScript 1.4.0
(function() {
  var area, circumference;

  area = function(radius) {
    return radius * radius * Math.PI;
  };

  circumference = function(radius) {
    return 2 * radius * Math.PI;
  };

  exports.area = area;

  exports.circumference = circumference;

}).call(this);
