// Generated by CoffeeScript 1.4.0
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(request, response) {
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return response.end('Hello World');
  });

  server.listen(3000);

  console.log('server running at localhost:3000');

}).call(this);